swagger: '2.0'
info:
  description: Describe the functionality
  version: 1.0.0
  title: Service title
  contact:
    name: Nome do LT responsável
    email: contato_responsavel@hdi.com.br
    url: 'http://hdixbbs1:7990/projects/nome-do-template-find-be'
  x-technical-owner: E-mail do Responsável Técnico
  x-api-key: API Key de associação ao serviço
host: api.template-find-be.endpoints.template-backoffice-dev.cloud.goog
basePath: /business_uinit/domain/v1
tags:
  - name: business domain
    description: Describe business activities
schemes:
  - https
security:
  - api_key: []
    oauth2_key: []
parameters:
  applicationId:
    in: header
    name: X-Application-Id
    required: true
    type: string
    description: Id of the Application that is using the API.
  userId:
    in: header
    name: X-User-Id
    required: true
    type: string
    description: Id of the User that is using the API.
  traceId:
    in: header
    name: X-Trace-Id
    required: true
    type: string
    description: Trace ID that is using the API.
  companyId:
    in: query
    name: companyId
    required: true
    type: string
    description: Id of the Company that is using the API.
  entity:
    in: body
    name: entity
    required: true
    description: description about entity
    schema:
      $ref: '#/definitions/Entity'
responses:
  200-Ok:
    description: Successful Request
    schema:
      $ref: '#/definitions/Entity'
  204-NoContent:
    description: No content responses
  400-BadRequest:
    description: Bad request
    schema:
      $ref: '#/definitions/ApiError'
  401-Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/ApiError'
  403-Forbidden:
    description: Forbidden
    schema:
      $ref: '#/definitions/ApiError'
  404-NotFound:
    description: Not found
    schema:
      $ref: '#/definitions/ApiError'
  405-DataInvalid:
    description: Data input not supplied or invalid
    schema:
      $ref: '#/definitions/ApiError'
  453-BusinessError:
    description: Business Exception
    schema:
      $ref: '#/definitions/BusinessError'
  500-Exception:
    description: Internal Server Error
    schema:
      $ref: '#/definitions/ApiError'
paths:
  /entity:
    get:
      tags:
        - business domain
      summary: entity
      description: entity
      operationId: getEntidadesAdd
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/applicationId'
        - $ref: '#/parameters/userId'
        - $ref: '#/parameters/traceId'
        - $ref: '#/parameters/companyId'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Entity'
definitions:
  ApiError:
    type: object
    description: Error API responses
    properties:
      code:
        type: integer
        format: int32
        description: Error ID
      message:
        type: string
        description: Error Description
      description:
        type: string
        description: Error Details
      errors:
        type: array
        description: Membership Erros
        items:
          $ref: '#/definitions/Error'
  BusinessError:
    type: object
    title: BusinessError
    description: Error API response
    properties:
      code:
        type: integer
        format: int32
        description: Error ID
      message:
        type: string
        description: Error Details
      description:
        type: string
        description: Error Details
      errors:
        type: array
        description: Membership Errors
        items:
          $ref: '#/definitions/Error'
      businessNotifications:
        type: array
        description: Membership Errors
        items:
          $ref: '#/definitions/BusinessNotifications'
  Error:
    type: object
    description: Error Entity
    properties:
      code:
        type: string
        description: Error ID
      message:
        type: string
        description: Error Description
      nativeMessage:
        type: string
        description: Native Error description
      trackid:
        type: string
        description: (Optional) Track ID of transaction
  BusinessNotifications:
    type: object
    description: Error Entity
    properties:
      code:
        type: string
        description: Error ID
      description:
        type: string
        description: Error Description
      type:
        type: string
        description: info | warning
  Entity:
    type: object
    description: Entity
    title: Entity
    properties:
      id:
        type: number
        format: int32
        description: id of Entity
      code:
        type: number
        format: int32
        description: code of de Entity
